<?php
require_once("../data/conf.php");
require_once("../data/airline.php");
require_once("../data/airlineclass.php");
require_once("../data/airports.php");
require_once("../data/DbHandler.php");
require_once("../data/specialluggage.php");
require_once("../data/trajecten.php");
require_once("../data/users.php");
require_once("../data/validator.php");
require_once("../data/ErrorLog.php");
?>